name: magen
description: "Open source israel alerts app"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  point_in_polygon: ^1.0.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.28.0
  firebase_messaging: ^14.8.0
  fluttertoast: ^8.2.4
  stacked: ^3.4.2
  animations: ^2.0.11
  injectable: ^2.4.1
  dynamic_themes: ^1.1.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  awesome_notifications_core: ^0.9.0 # <~ always ensure to use the latest version
  awesome_notifications: any # <~ this version is managed by awesome_notifications_core package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cities.json
    - assets/polygons.json
    - assets/threats.json
    - .env