/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        dark: {
          'color-scheme': 'dark',
          primary: '#1565c0',
          'primary-content': '#fff',
          secondary: '#7b1fa2',
          'secondary-content': '#fff',
          accent: '#1F262E',
          'accent-content': '#fff',
          neutral: '#556474',
          'neutral-content': '#FEFEFF',
          'base-100': '#111419',
          'base-200': '#1E272E',
          'base-300': '#1F272A',
          'base-content': '#ffffff',
          info: '#01579b',
          'info-content': '#ffffff',
          success: '#1b5e20',
          'success-content': '#ffffff',
          warning: '#e65100',
          'warning-content': '#ffffff',
          error: '#c62828',
          'error-content': '#ffffff',
        },
        light: {
          'color-scheme': 'light',
          primary: '#3299FE',
          'primary-content': '#D9E9F8',
          secondary: '#7b1fa2',
          'secondary-content': '#D9E9F8',
          accent: '#0B6BCB',
          'accent-content': '#D9E9F8',
          neutral: '#303740',
          'neutral-content': '#D9E9F8',
          'base-100': '#FEFEFF',
          'base-200': '#F5FAFF',
          'base-300': '#E5F6FD',
          'base-content': '#111419',
          info: '#03a9f4',
          'info-content': '#ffffff',
          success: '#4caf50',
          'success-content': '#ffffff',
          warning: '#ff9800',
          'warning-content': '#ffffff',
          error: '#ef5350',
          'error-content': '#ffffff',
        },
      }
    },
  },
  plugins: [],
}

