services:
  ws:
    init: false
    image: thewh1teagle/magen-srv:latest
    entrypoint: /usr/local/bin/server -a "0.0.0.0" -p 3030
    depends_on:
      - nginx
    restart: unless-stopped
    stop_grace_period: 1s
    environment:
      - RUST_LOG=info
      - TZ=Asia/Jerusalem

  ws_mock:
    init: false
    image: thewh1teagle/magen-srv:latest
    entrypoint: /usr/local/bin/server -a "0.0.0.0" -p 3030 -m --interval 10s
    depends_on:
      - nginx
    
    restart: unless-stopped
    stop_grace_period: 1s
    environment:
      - RUST_LOG=info
      - TZ=Asia/Jerusalem
      
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    environment:
      - DOMAIN
      - TZ=Asia/Jerusalem
    ports:
      - 80:80
      - 443:443 # mapping port 443 to the container's port 443 for https
    volumes:
      - ./etc/nginx/templates:/etc/nginx/templates:ro
      - ./etc/letsencrypt:/etc/letsencrypt:ro # mounting the folder to the nginx container 
      - ./certbot/data:/var/www/certbot

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >-
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email ${EMAIL} --agree-tos --no-eff-email
             -d ${DOMAIN}
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Etc/UTC #optional
      - SUBDOMAINS=oref-rs.duckdns.org
      - TOKEN=${DUCKDNS_TOKEN}
      - LOG_FILE=false #optional
    env_file:
      - .env
    restart: unless-stopped
