services:
  bot:
    init: false
    image: thewh1teagle/magen_bot:latest
    build:
      context: ../
      dockerfile: telegram_bot/Dockerfile
    env_file:
      - .env
    environment:
      - LOG_LEVEL=DEBUG
    network_mode: "host"
    restart: unless-stopped
